name: 'Action Items Sync'
description: 'Extract action items from multiple issues and aggregate them into 1'
inputs:
  org:
    description: 'Repository Owner (User or Organization)'
    required: false

  repo:
    description: 'Repository name'
    required: false

  issue-number:
    description: 'Issue Number'
    required: true

  token:
    description: 'Access token'
    required: true

outputs:
  result:
    description: 'Result of the command executed'

runs:
  using: 'node12'
  main: 'dist/index.js'
